language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - npm update
script:
  - npm test
  - npm run build
  - npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master